name       : perl-module-pluggable
version    : 5.2
release    : 7
source     :
    - http://search.cpan.org/CPAN/authors/id/S/SI/SIMONW/Module-Pluggable-5.2.tar.gz : b3f2ad45e4fd10b3fb90d912d78d8b795ab295480db56dc64e86b9fa75c5a6df
license    : Artistic-1.0-Perl
component  : programming.perl
summary    : Module::Pluggable - automatically give your module the ability to have plugins
description: |
    Module::Pluggable - automatically give your module the ability to have plugins
builddeps  :
    - perl
setup      : |
    %perl_setup
build      : |
    %perl_build
install    : |
    %perl_install
